### ISSUE TITLE
mpdf/mpdf versão 7

### ISSUE THREAD

**Issue by leoizepi** [PronerInformatica/phppimaco#11]
Não funcionando na versão 7.2 com mpdf 7

**Comment by edsonrodsilva** [comment]
I'm getting this error while updating the PHP version.
Error PHP 7.2: count (): Parameter must be an array or an object that implements Countable
Someone else is also having this error.

**Comment by LiorMesser** [comment]
Aqui comigo a nova eelease funcionou perfeitamente, mPDF 7 e PHP 7.2
