### ISSUE TITLE
Parâmetro "align" no config.json

### ISSUE THREAD

**Issue by LiorMesser** [PronerInformatica/phppimaco#12]
Antes de mais nada, me desculpe pois sou novato na área... Dá uma olhada nesse código da Tag.php, linhas  55 a 57
if(isset($std->tag->ln)){
   $this->align = $std->tag->align;
}

Não deveria ser if(isset($std->tag->align)? Eu alterei isso e incluí o parâmetro "align" em um dos templates. Usei "align" : "center" e funcionou perfeitamente!

Reparei também que essas linhas, na mesma Tag.php, estão duplicadas nas linhas 43-45 e 47-49:
        if( empty($this->padding) ){
            $this->padding = 0;
        }

**Comment by dbemfica** [comment]
Verdade @LiorMesser 

Mancada minha, obrigado pela dica
