### ISSUE TITLE
Tamanho de página com erro

### ISSUE THREAD

**Issue by LiorMesser** [PronerInformatica/phppimaco#13]
Na Pimaco.php, linha 70 o código:
`'margin_footer' => $this->marginBottom`
Deveria ser:
`'margin_bottom' => $this->marginBottom`

Eu acertei isso e parou de pular a última linha de etiquetas. O código errado acima estava definindo um margin_footer de 12.7 mm e usando o margin_bottom default de 16 mm, o que causava a quebra de página antes da última linha de etiquetas.

**Comment by dbemfica** [comment]
Verdade @LiorMesser 

Mancada minha, obrigado pela dica
