### ISSUE TITLE
Construtor da classe Pimaco não aceita outro tempDir

### ISSUE THREAD

**Issue by victordeaguiarsouza** [PronerInformatica/phppimaco#17]
Tentei fazer um pullrequest mas não foi.
Se for interessante modificar o construtor para aceitar um tempDir diferente do padrão para class Mpdf, o código está abaixo. Testado.
Vou tentar outro pullrequest amanhã.

Desde já agradeço. Obrigado.

public function __construct($template, $path_template = null, $tempDir = null)
    {
        $this->path_template = dirname(__DIR__) . "/templates/";
        if (!empty($path_template)) {
            $this->path_template = $path_template;
        }
        $this->file_template = $template.".json";
        $this->loadConfig();

        $this->tags = new \ArrayObject();

        $config = [
            'format' => [$this->width, $this->height],
            'default_font_size' => $this->fontSize,
            'margin_left' => $this->marginLeft,
            'margin_right' => $this->marginRight,
            'margin_top' => $this->marginTop,
            'margin_bottom' => $this->marginBottom,
            'margin_header' => $this->marginHeader,
            'margin_footer' => $this->marginFooter
        ];
        
        if(!empty($tempDir)) $config['tempDir'] = $tempDir;

        $this->pdf = new Mpdf($config);
    }

**Comment by dbemfica** [comment]
Ola @victordeaguiarsouza 

Não sei bem pq o seu Pull Request não passou

Mas de qualquer forma eu adicionei as suas modificações na lib. Realmente me parece estar tudo certo, Se poder testar e se tudo estiver certo fechar a Issue eu agraço.

Obrigado pela contribuição.

**Comment by victordeaguiarsouza** [comment]
O código está OK. Acabei de testar.
Eu que agradeço pela sua atenção @dbemfica .
