### ISSUE TITLE
Release v1.3.3 não está baixando no composer

### ISSUE THREAD

**Issue by victordeaguiarsouza** [PronerInformatica/phppimaco#18]
Quando rodei o composer pra pegar a v1.3.3.
Só puxa até a v1.3.1.
Linha do meu composer: "proner/phppimaco" : "^1.3.1"

Se tentar forçar na v1.3.3 dá a seguinte mensagem.

Problem 1
    - The requested package proner/phppimaco ^1.3.3 exists as proner/phppimaco[dev-master, v0.1.0, v0.2.0, v0.2.1, v0.3.1, v0.3.2, v0.4.2, v1.0.0, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1] but these are rejected by your constraint.

Já tentei remover o pacote proner/phppimaco e rodar o composer novamente. Sem sucesso.

**Comment by dbemfica** [comment]
Precisei atualizar packagist na mão

Tente agora

 com o comando 

```php
composer require proner/phppimaco:1.3.3
```

**Comment by victordeaguiarsouza** [comment]
Sucesso meu amigo.
Obrigado.
