### ISSUE TITLE
HTML várias etiquetas

### ISSUE THREAD

**Issue by darlanthiago** [PronerInformatica/phppimaco#20]
Boa tarde, o HTML para a geração de várias etiquetas, assim como o PDF, está funcionando ??

**Comment by dbemfica** [comment]
Boa tarde, é para estar, você teve algum problema?

**Comment by darlanthiago** [comment]
Olá Diego, obrigado por responder. Antes de mostra, queria agradecer pela sua excelente biblioteca. Ela funciona muito bem, porém, eu preciso gerar umas 80 etiquetas de uma vez, por pdf fica inviável devido à quantidade de memória RAM que consome para gerar PDF. Então decidi jogar o html na página mesmo. Porém fica com quebra de layout na impressão.

[cid:image003.jpg@01D60E92.B34DC200]

Esse é o código que estou fazendo.

[cid:image002.png@01D60E92.B33A12F0]

De: Diogo Bemfica <notifications@github.com>
Enviada em: quinta-feira, 9 de abril de 2020 17:05
Para: PronerInformatica/phppimaco <phppimaco@noreply.github.com>
Cc: Darlan Thiago <tdarlan1@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [PronerInformatica/phppimaco] HTML várias etiquetas (#20)


Boa tarde, é para estar, você teve algum problema?

**Comment by darlanthiago** [comment]
![Untitled](https://user-images.githubusercontent.com/36196918/78940621-8abeed80-7a8c-11ea-8cd9-ab41cefd3509.png)

**Comment by darlanthiago** [comment]
![Untitled2](https://user-images.githubusercontent.com/36196918/78940710-ae823380-7a8c-11ea-9a30-ed16947cfdb7.png)

**Comment by dbemfica** [comment]
@darlanthiago  Vou dar uma olhada e fazer uns testes aqui para tentar resolver o seu problema

**Comment by darlanthiago** [comment]
Blz, fico muito agradecido Diogo

**Comment by dbemfica** [comment]
@darlanthiago Estava dando uma olhada, mas parece que realmente exportar para HTML não está funcionando.

Mas fiz umas esperiencias com a lib em um fork e acredito que agora você vai conseguir gerar os PDF mesmo.

Peço que tu tente usar o fork, só trocar no seu composer 

 proner/phppimaco -> dbemfica/phppimaco

para ver se foi resolvido o seu problema

Aguardo seu retorno

**Comment by darlanthiago** [comment]
Farei alguns testes Diogo e te dou retorno, muito obrigado

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dbemfica** [comment]
@darlanthiago Deu certo os ajustes? Posso fechar essa issue?

**Comment by darlanthiago** [comment]
Opa, desculpa esqueci de responder pois tive que parar o projeto por uns dias.

Pelo que vi Diogo, ficou a mesma coisa ainda. Sempre que executo o html em tela, quebra o layout de impressão.

De: Diogo Bemfica <notifications@github.com>
Enviada em: domingo, 31 de maio de 2020 18:48
Para: PronerInformatica/phppimaco <phppimaco@noreply.github.com>
Cc: Darlan Thiago <tdarlan1@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [PronerInformatica/phppimaco] HTML várias etiquetas (#20)


@darlanthiago<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdarlanthiago&data=02%7C01%7C%7Cedd933ce9e7b4d36059408d805ac3d0b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637265584594200217&sdata=5oFqo1vlzK9p8RBBjXte6jE4nQA7bVgQNLzbtbZjgo0%3D&reserved=0> Deu certo os ajustes? Posso fechar essa issue?

**Comment by dbemfica** [comment]
@darlanthiago Eu fiz umas melhorias na quantidade de memoria usada, agora tu deve conseguir fazer a impressão em pdf mesmo, tu poderia testar para ver se resolveu o teu problema?
