### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by eternogold5** [PronerInformatica/phppimaco#3]
Boa tarde,

Gostaria de saber como faz para implemetar essa biblioteca no codeigniter

**Comment by dbemfica** [comment]
Boa tarde

Não conheço muito do CodeIgniter, mas acredito que a forma mais simples de implementar é extasiando classe em um controller e usar o método output() ao invés de um load->view.

Sei que não a forma mais adequada mas isso deve funcionar.

**Comment by dbemfica** [comment]
Posso fechar a issue?

**Comment by eternogold5** [comment]
Pode sim

Em 8 de fev de 2018 15:16, "Diogo Bemfica" <notifications@github.com>
escreveu:

**Comment by dbemfica** [comment]
Tu conseguiu resolver o seu problema?
