### ISSUE TITLE
Uso com CakePHP

### ISSUE THREAD

**Issue by marcions** [PronerInformatica/phppimaco#4]
Montei o exemplo no CakePHP e está apresentando os erros abaixo:

Notice (8): Undefined property: stdClass::$ln [ROOT\vendor\proner\phppimaco\src\Tag.php, line 51]
Notice (8): Undefined property: stdClass::$align [ROOT\vendor\proner\phppimaco\src\Tag.php, line 52]
Notice (8): Undefined property: stdClass::$ln [ROOT\vendor\proner\phppimaco\src\Tag.php, line 51]
Notice (8): Undefined property: stdClass::$align [ROOT\vendor\proner\phppimaco\src\Tag.php, line 52]
Notice (8): A non well formed numeric value encountered [ROOT\vendor\mpdf\mpdf\mpdf.php, line 30572]
Notice (8): A non well formed numeric value encountered [ROOT\vendor\mpdf\mpdf\mpdf.php, line 30572]

**Comment by dbemfica** [comment]
Boa tarde @marcions 

Me parece ser um problema no carregamento no template de configuração.

Tu poderia compartilhar o código para eu dar uma olhada?

**Comment by marcions** [comment]
Vou refazer o código e compartilho, pois acabei excluindo para tentar com outros métodos

**Comment by dbemfica** [comment]
Ok, fico no aguardo
