### ISSUE TITLE
Abandoned dependency

### ISSUE THREAD

**Issue by kidh0** [PronerInformatica/phppimaco#9]
When you install the plugin there is a dependency that is abandoned (moved to a different repository or renamed). 

`Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead.`

I didn't dig too deep into the issue to see if it is not as simple as update the composer file, but since the current version on the project is 1.7 and the latest version is 3.*, I think that it needs a little bit of testing

**Comment by dbemfica** [comment]
@kidh0 Thanks for the feedback, I'll check this pending

**Comment by dbemfica** [comment]
resolved
